spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost/somedb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update